language: python
python:
    - "3.7"
    - "3.8"

addons:
  apt:
    packages:
      - portaudio19-dev

install:
    - pip install poetry coveralls
    - poetry install -v

script:
    - poetry run mypy .
    - poetry run coverage run -m pytest --full-trace --showlocals

after_success:
    coveralls
