language: python
python:
    - "3.7"
    - "3.8"

addons:
  apt:
    packages:
      - portaudio19-dev

install:
    - pip install poetry coveralls
    - poetry install -v

script:
    - make mypy
    - make test-coverage

after_success:
    coveralls
